#!/bin/bash

SCRIPT_PATH="${BASH_SOURCE[0]}";
SCRIPT_DIR=$(dirname $SCRIPT_PATH)

cd $SCRIPT_DIR
source ../control/${PROJ}_bashrc

running "procmap -instance $PROJ"
if [[ $? == 1 ]]; then
    echo "Starting procmap"
    procmap -instance $PROJ &
fi
