#!/bin/bash

proc_name=$1
instance=$2
sub_dir=$3

if [ "$sub_dir" = no-params ]
then

  running "$proc_name -instance $instance"
  if [ $? = 1 ]; then
    $proc_name -instance $instance 2>&1 | \
      LogFilter -d $ERRORS_LOG_DIR -p $proc_name -i $instance &
  fi


else
    
    cd $RAP_PROJ_DIR
    if [[ -d "config" ]]; then
	cd config
    else
	cd params
    fi
    [[ -d $sub_dir ]] && cd $sub_dir
    if [[ -f $proc_name.$instance ]]; then
	running "$proc_name -params $proc_name.$instance"
	if [ $? = 1 ]; then
	    $proc_name -params $proc_name.$instance 2>&1 | \
		LogFilter -d $ERRORS_LOG_DIR -p $proc_name -i $instance &
	fi
    else
	echo "Cannot find param_file $proc_name.$instance"
    fi
fi

